; PlatformIO Project Configuration File for RP2040 / Pico Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
upload_protocol = picotool
