; PlatformIO Project Configuration File
; Generated automatically by MCU Flasher by Naph

[platformio]
default_envs = mcu_flash_esp32s3_dev_module

[env:mcu_flash_esp32s3_dev_module]
platform = espressif32

board = esp32-s3-devkitc-1

framework = arduino

monitor_speed = 115200


upload_protocol = esptool

board_build.flash_mode = dio

build_flags =
    -D NETWORK_PROV_SCHEME_SOFTAP=WIFI_PROV_SCHEME_SOFTAP
    -D NETWORK_PROV_SCHEME_HANDLER_NONE=WIFI_PROV_SCHEME_HANDLER_NONE
    -D NETWORK_PROV_SECURITY_1=WIFI_PROV_SECURITY_1

lib_extra_dirs = C:/Users/napht/Documents/_MCUFlasherByNaph_src/Libs

board_build.partitions = huge_app.csv
