; PlatformIO Project Configuration File for STM32 Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = ststm32
board = nucleo_f401re
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
