; PlatformIO Project Configuration File for Nordic nRF52 Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = nordicnrf52
board = nrf52840_dk
framework = arduino
monitor_speed = 115200
upload_protocol = jlink
