; PlatformIO Project Configuration File for ESP8266 Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
