; PlatformIO Project Configuration File
; Generated automatically by MCU Flasher by Naph

[platformio]
default_envs = mcu_flash

[env:mcu_flash]
platform = espressif32

board = esp32dev

framework = arduino

monitor_speed = 115200

upload_speed = 921600

build_flags =
    -D NETWORK_PROV_SCHEME_SOFTAP=WIFI_PROV_SCHEME_SOFTAP
    -D NETWORK_PROV_SCHEME_HANDLER_NONE=WIFI_PROV_SCHEME_HANDLER_NONE
    -D NETWORK_PROV_SECURITY_1=WIFI_PROV_SECURITY_1

lib_extra_dirs = D:/QuickAccess/NAPH/Documents/_MCUFlasherByNaph_src/Libs

lib_deps =
    D:/QuickAccess/NAPH/Documents/_MCUFlasherByNaph_src/Libs/FastAccelStepper-1.2.5
    D:/QuickAccess/NAPH/Documents/_MCUFlasherByNaph_src/Libs/ESP32Servo-3.2.1

board_build.partitions = huge_app.csv
