; PlatformIO Project Configuration File for Renesas RA / Arduino UNO R4 Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
monitor_speed = 115200
