"""Project ownership and native hidden-file checks in isolated temp fixtures."""
from __future__ import annotations

import ctypes
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import Mock, patch

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from main.core import file_utils


class HygieneChecks(unittest.TestCase):
    def setUp(self):
        audit = ROOT / "temp/audit/project-hygiene"
        audit.mkdir(parents=True, exist_ok=True)
        self.temp = tempfile.TemporaryDirectory(dir=audit)
        self.addCleanup(self.temp.cleanup)
        self.project = Path(self.temp.name)

    def create(self, name, text="user-owned"):
        path = self.project / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def attributes(self, path):
        return ctypes.windll.kernel32.GetFileAttributesW(str(path))

    @unittest.skipUnless(sys.platform == "win32", "Native Windows attributes")
    def test_generated_updates_stay_hidden_and_writable(self):
        target = self.project / "AGENTS.md"
        file_utils.write_generated_text(target, "first")
        self.assertTrue(self.attributes(target) & 0x02)
        file_utils.write_generated_text(target, "updated")
        self.assertEqual(target.read_text(), "updated")
        self.assertTrue(self.attributes(target) & 0x02)
        self.assertFalse(self.attributes(target) & 0x01)
        self.assertEqual([p.name for p in self.project.iterdir()], ["AGENTS.md"])

    @unittest.skipUnless(sys.platform == "win32", "Native Windows attributes")
    def test_writable_helper_preserves_hidden_and_system(self):
        path = self.create("owned.json")
        file_utils._set_windows_file_attributes(path, 0x01 | 0x02 | 0x04)
        file_utils.ensure_file_writable(path)
        self.assertEqual(self.attributes(path) & 0x07, 0x02 | 0x04)

    def test_failed_atomic_update_keeps_old_content(self):
        target = self.create("metadata.json", "keep")
        with patch.object(file_utils.os, "replace", side_effect=RuntimeError("Locked")):
            with self.assertRaises(RuntimeError):
                file_utils.write_generated_text(target, "new")
        self.assertEqual(target.read_text(), "keep")
        self.assertFalse(list(self.project.glob(".mcu-generated-*.tmp")))

    def test_reconciliation_hides_generated_entries_and_preserves_user_files(self):
        owned = [
            self.create("AGENTS.md", "Generated automatically by MCU Flash GUI"),
            self.create(".opencodeignore", "# Auto-generated by MCU Flash GUI"),
            self.create("compile_commands.json", '[{"directory":"./.mcu_flasher_build_cache/boards/demo"}]'),
            self.create(".clangd", "CompilationDatabase: .mcu_flasher_build_cache/boards/demo"),
            self.create(".pio_bootstrap_first_use_demo", "ready"),
        ]
        vscode = self.create(".vscode/c_cpp_properties.json", '{"compilerPath":"./.platformio-mcu-gui/toolchain/g++"}').parent
        cache = self.create(".mcu_flasher_build_cache/object.o").parent
        users = [self.create(name) for name in ("sketch.ino", "sensor.cpp", "sensor.h", "NOTE.txt", "READ-FIRST.md", "SKILL.md", "settings.json", "src/helper.cpp", "assets/photo.png")]
        with patch.object(file_utils, "_migrate_legacy_project_generated_files", return_value=cache), patch.object(file_utils, "ensure_hidden_read_first_md"):
            file_utils.hide_internal_project_metadata(self.project)
            file_utils.hide_internal_project_metadata(self.project)
        for path in users:
            self.assertEqual(path.read_text(), "user-owned")
        if sys.platform == "win32":
            for path in (*owned, vscode, cache):
                self.assertTrue(self.attributes(path) & 0x02, str(path))
            for path in users:
                self.assertFalse(self.attributes(path) & 0x02, str(path))
            for name in ("src", "assets"):
                self.assertFalse(self.attributes(self.project / name) & 0x02)
            self.assertFalse(self.attributes(cache / "object.o") & 0x02, "Hide the container without walking its children")

    def test_user_ide_configuration_does_not_become_generated(self):
        cache = self.project / ".mcu_flasher_build_cache"
        users = [self.create("AGENTS.md", "My project rules"),
                 self.create("compile_commands.json", '[{"directory":"./build"}]'),
                 self.create(".clangd", "CompileFlags: {Add: [-Wall]}"),
                 self.create(".vscode/settings.json", '{"editor.tabSize":2}')]
        with patch.object(file_utils, "_migrate_legacy_project_generated_files", return_value=cache), patch.object(file_utils, "ensure_hidden_read_first_md"), patch.object(file_utils, "hide_hidden_attribute") as hide, patch.object(file_utils, "hide_generated_directory") as directory:
            file_utils.hide_internal_project_metadata(self.project)
        for path in users:
            self.assertFalse(file_utils._is_mcu_generated_ide_metadata(path))
            self.assertNotIn(path, [c.args[0] for c in hide.call_args_list])
        self.assertNotIn(self.project / ".vscode", [c.args[0] for c in directory.call_args_list])

    def test_instruction_generation_repeated_writes_remain_readable(self):
        with patch.object(file_utils, "SCRIPT_DIR", self.project / "app"):
            file_utils.ensure_hidden_read_first_md(self.project)
            file_utils.ensure_hidden_read_first_md(self.project)
        agents = self.project / "AGENTS.md"
        self.assertIn("Generated automatically by MCU Flash GUI", agents.read_text(encoding="utf-8"))
        self.assertTrue((self.project / ".opencode/skills/sketch-workflow/SKILL.md").exists())
        if sys.platform == "win32":
            for name in ("AGENTS.md", ".opencodeignore", ".opencode", ".agents", ".mcu_flasher_build_cache"):
                self.assertTrue(self.attributes(self.project / name) & 0x02, name)

    def test_generator_preserves_user_instructions_and_ignore_rules(self):
        users = [self.create("AGENTS.md", "My project rules"), self.create(".opencodeignore", "My own excludes")]
        with patch.object(file_utils, "SCRIPT_DIR", self.project / "app"):
            file_utils.ensure_hidden_read_first_md(self.project)
        self.assertEqual(users[0].read_text(), "My project rules")
        self.assertEqual(users[1].read_text(), "My own excludes")
        if sys.platform == "win32":
            for path in users:
                self.assertFalse(self.attributes(path) & 0x02)


if __name__ == "__main__":
    unittest.main(verbosity=2)
