/* Execute the actual Monaco font scripts with isolated editor/bridge fixtures. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, '../src/editor/index.html'), 'utf8');
const zoomStart = html.indexOf('      window.__mcuEditorFontSize = 13;');
const zoomEnd = html.indexOf('      function handleZoom(e)', zoomStart);
const setterStart = html.indexOf('      window.setEditorFontSize = function ');
const setterEnd = html.indexOf('      async function autoInitTheme()', setterStart);
assert(zoomStart > 0 && zoomEnd > zoomStart && setterStart > 0 && setterEnd > setterStart);
const saved = [], sizes = [];
const window = {editorBridge: {save_font_size: size => saved.push(size)}};
const context = vm.createContext({window, console});
vm.runInContext(html.slice(zoomStart, zoomEnd) + html.slice(setterStart, setterEnd), context);
window.setEditorFontSize(22);
assert.equal(window.__mcuEditorFontSize, 22, 'Remember saved font before Monaco is ready');
window.editorInstance = {updateOptions: options => sizes.push(options.fontSize), layout() {}};
window.setEditorFontSize(window.__mcuEditorFontSize);
assert.equal(sizes.at(-1), 22);
vm.runInContext('zoomMonaco(1)', context);
assert.equal(sizes.at(-1), 23, 'Zoom must step from the restored font, not hardcoded 13');
assert.equal(saved.at(-1), 23);
window.setEditorFontSize(48);
vm.runInContext('zoomMonaco(1)', context);
assert.equal(sizes.at(-1), 48);
window.setEditorFontSize(6);
vm.runInContext('zoomMonaco(-1)', context);
assert.equal(sizes.at(-1), 6);
vm.runInContext('zoomMonaco(0)', context);
assert.equal(sizes.at(-1), 13);
window.setEditorFontSize('not a number');
assert.equal(window.__mcuEditorFontSize, 13);
// Raw WebChannel callback failures roll back to the last confirmed choice.
const callbacks = [];
window.editorBridge.save_font_size = (size, callback) => callbacks.push({size, callback});
window.setEditorFontSize(22);
vm.runInContext('zoomMonaco(1)', context);
callbacks.shift().callback({success: false});
assert.equal(sizes.at(-1), 22);
assert.equal(window.__mcuEditorFontSize, 22);
vm.runInContext('zoomMonaco(1); zoomMonaco(1)', context);
callbacks.shift().callback({success: false});
assert.equal(window.__mcuEditorFontSize, 24, 'Old failure must not undo a newer zoom');
callbacks.shift().callback({success: false});
assert.equal(window.__mcuEditorFontSize, 22, 'Two failed saves restore the actual last saved font');
vm.runInContext('zoomMonaco(1); zoomMonaco(1)', context);
callbacks.shift().callback({success: true});
callbacks.shift().callback({success: false});
assert.equal(window.__mcuEditorFontSize, 23, 'Latest failure preserves an earlier confirmed save');
vm.runInContext('zoomMonaco(1)', context);
window.setEditorFontSize(27);
callbacks.shift().callback({success: false});
assert.equal(window.__mcuEditorFontSize, 27, 'Failure must not undo an external saved-font update');
vm.runInContext('zoomMonaco(1)', context);
window.setEditorFontSize(30);
callbacks.shift().callback({success: true});
assert.equal(window.__mcuSavedEditorFontSize, 30, 'Old save acknowledgement cannot replace a newer external saved font');
window.setEditorFontSize(27);

async function promiseChecks() {
  delete window.editorBridge;
  let resolveSave;
  window.pywebview = {api: {save_font_size: () => new Promise(resolve => { resolveSave = resolve; })}};
  vm.runInContext('zoomMonaco(1)', context);
  resolveSave({success: false});
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(window.__mcuEditorFontSize, 27, 'Proxy Promise failure rolls back');
  window.pywebview.api.save_font_size = () => Promise.reject(new Error('fixture write failure'));
  vm.runInContext('zoomMonaco(1)', context);
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(window.__mcuEditorFontSize, 27, 'Proxy rejection rolls back without another save');
  console.log('Editor font restore, zoom, bounds, raw/Promise failures and latest-choice guards OK');
}
promiseChecks().catch(error => { console.error(error); process.exitCode = 1; });
