; PlatformIO Project Configuration File
; Generated automatically by MCU Flash GUI

[platformio]
default_envs = mcu_flash

[env:mcu_flash]
platform = espressif32

board = esp32dev

framework = arduino

monitor_speed = 115200

upload_speed = 921600

build_flags =
    -D NETWORK_PROV_SCHEME_SOFTAP=WIFI_PROV_SCHEME_SOFTAP
    -D NETWORK_PROV_SCHEME_HANDLER_NONE=WIFI_PROV_SCHEME_HANDLER_NONE
    -D NETWORK_PROV_SECURITY_1=WIFI_PROV_SECURITY_1

lib_extra_dirs = C:/Users/ADMIN/Documents/_MCUFlasherByNaph_src/Libs

lib_deps =
    ../../../.pio/libdeps/esp32da/ESP32Servo
    ../../../.pio/libdeps/esp32da/FastAccelStepper
    ../../../.pio/libdeps/esp32da/HX711

board_build.partitions = huge_app.csv

