; PlatformIO Project Configuration File for SAM / SAMD Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = atmelsam
board = zeroUSB
framework = arduino
monitor_speed = 115200
upload_protocol = sam-ba
