; PlatformIO Project Configuration File for Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_speed = 115200
