; PlatformIO Project Configuration File for Teensy Soft Reset
[platformio]
src_dir = .
default_envs = mcu_flash

[env:mcu_flash]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
